version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: crud-api-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7.29
    container_name: crud-api-mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "7088:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${DB_DATABASE}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db-mysql5.7-volume:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-api-php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  adminer:
    container_name: crud-api-adminer
    image: adminer
    restart: always
    ports:
      - "7089:8080"
    depends_on:
      - mysql
volumes:
  db-mysql5.7-volume:
